name: Create Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create release zip
      run: |
        zip -r rpc4stalker-${{ github.event.inputs.build-ver }}.zip gamedata licences README.md rpc4games.cfg

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.build-ver }}
        release_name: Release ${{ github.event.inputs.build-ver }}
        files: rpc4stalker-${{ github.event.inputs.build-ver }}.zip
        draft: false
        prerelease: false
